### ISSUE TITLE
検索機能をつけると、テーブルが表示されない

### ISSUE THREAD

**Issue by YosukeOnuma** [kaijo-programming-ios/app2017#1]
検索機能を企画一覧のページに作ると、なぜかテーブルが表示されなくなった。
現状はtableBugFixブランチに6/11にプッシュされたもの。
ということで、まずteratailで質問中。[ここ](https://teratail.com/questions/79902)
また、ブランチで検索機能を分け、メインで他に取り掛かろうと思う。

**Comment by babcs2035** [comment]
すみません、まだ対応出来そうにありません...
なお、master ブランチで作業はしない方がいいです。

**Comment by babcs2035** [comment]
とりあえず、こちらでも実際に再現してみようと思います。

**Comment by YosukeOnuma** [comment]
え、マスターで作業しないほうがいいの？なんで？

2017-06-11 19:36 GMT+09:00 Bwambocos <notifications@github.com>:

**Comment by babcs2035** [comment]
26515d3ab5de04412beb243412a6652cf3a392f2
↑このコミットで変更したソースコードの中の ? の部分の関数の意味を教えていただけませんでしょうか？

**Comment by YosukeOnuma** [comment]
どっちも、テーブルが表示されないバグを直そうとして追加したもの。
```
func numberOfSections(in tableView: UITableView) -> Int {
 　       return searchResult2.count
}
```
は、「セクション数が0だと表示されない」という記事を見て、整数や変数で再定義したもの。

```
 override func viewWillAppear(_ animated: Bool) {
          self.table.reloadData()
          super.viewWillAppear(animated)
}
```
これは、テーブルの情報を更新すればうまくいくのかな？と思って、
[あるタイミング](http://d.hatena.ne.jp/cooking_3min/20121129/1354176847)で情報更新をしようとしたもの。

**Comment by babcs2035** [comment]
詳しい説明ありがとうございます。
また明日以降考えていきたいと思います。
話が変わるのですが、新しく develop ブランチを作成しました。日頃の開発・実装が終了した段階で、develop ブランチにプルリクエストを出すようにするのはいかがでしょうか？

**Comment by babcs2035** [comment]
#4 にてプルリクエストを出しておきました。
これにて、Close とします。
バグ修正ありがとうございました。

**Comment by babcs2035** [comment]
まだ、解決されていないようでしたので、Reopen させていただきます。

**Comment by babcs2035** [comment]
@YosukeOnuma  12bca2aeb905d2dabded2606ba7874f2a9051607
このコミットにて、検索機能実装時にテーブルが表示されなくなるバグを修正しました。
しかし、企画名と団体名は表示できているのですが、サムネイル画像の表示の仕方が分からないため、まだ実装していません。調べて今週中には検索部分は完成させ、プルリクエストを出したいと思います。

**Comment by YosukeOnuma** [comment]
おおお！本当にありがとう！
ただ、よくわからないけどうまくPullできないから、実際の確認はちょっと待ってね。

2017年6月15日 6:49 Bwambocos <notifications@github.com>:

**Comment by YosukeOnuma** [comment]
試験お疲れ様。
未だになぜかうまくPullできないんだけど、そっちのパソコンでバグは直ってるの？

**Comment by babcs2035** [comment]
はい。バグは発生していません。

<img width="1280" alt="2017-07-10 19 49 54" src="https://user-images.githubusercontent.com/22171273/28014951-0017c544-65a9-11e7-85e7-0f9ea81be012.png">

**Comment by babcs2035** [comment]
#5 にてプルリクエストを出しました。

**Comment by YosukeOnuma** [comment]
すごい！直ってる！ありがとう！
ちなみにどこが原因だったかわかる？

**Comment by babcs2035** [comment]
もう一度 Storyboard での部品配置とコードを書き直したらうまく治ったと思います。
うまくいかないときは一からやり直してみるのもいいかもしれません。
