### ISSUE TITLE
端末を横向きにした時の挙動について

### ISSUE THREAD

**Issue by babcs2035** [kaijo-programming-ios/app2017#2]
僕の iPhone 6 で実行してみたのですが、横向きにすることが可能のようで、レイアウトが崩れて表示されます。なので、アプリ全体を横向きにすることをできなくし、縦向きだけにすべきではないでしょうか。

**Comment by YosukeOnuma** [comment]
うん、横向きで使うことはないだろうし、そのほうがいいと思う。
ちなみにどうやって横向きを無効化するの？

**Comment by babcs2035** [comment]
SetOrientation ブランチにて実装しました。
プルリクエストを出しておきます。
#3

**Comment by babcs2035** [comment]
#3 にて解決したので、close とします。
