### ISSUE TITLE
企画詳細への画面遷移

### ISSUE THREAD

**Issue by babcs2035** [kaijo-programming-ios/app2017#6]
Table の Cell が表示されないバグを治したところ、今度は企画の詳細画面への遷移ができなくなってしまっていました。調べたところ、SeResultViewController.swift の prepare() が呼ばれていませんでした。このバグは new_detailPage で発生しています。

**Comment by YosukeOnuma** [comment]
僕もそれで悩んでいる。。。
頑張って調べます。

**Comment by babcs2035** [comment]
このコミットにてバグを修正しました。
a72fe54999e30e2e1dd5c9ceb7d0d035b2671dbd

**Comment by YosukeOnuma** [comment]
ありがとう。
プルリクエストお願い。

2017-07-23 13:16 GMT+09:00 Bwambocos <notifications@github.com>:
